# docker-compose.prod.yml
version: '3.8'

services:
  strapi:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: strapi-prod
    expose:
      - "1337"
    volumes:
      - uploads-volume:/app/public/uploads
      - data-volume:/app/.tmp
    environment:
      NODE_ENV: production
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:1337/_health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - coolify
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.strapi.rule=Host(`premiarteserver.lumau.com.ar`)"
      - "traefik.http.routers.strapi.entrypoints=http,https"
      - "traefik.http.services.strapi.loadbalancer.server.port=1337"
  
networks:
  coolify:
    external: true

volumes:
  uploads-volume:
  data-volume: