# docker-compose.prod.yml
version: '3.8'

services:
  strapi:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: strapi-prod
    expose:
      - "1337"
    volumes:
      - uploads-volume:/app/public/uploads
      - data-volume:/app/.tmp
    environment:
      NODE_ENV: production
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:1337/_health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - coolify
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.premiarteserver.rule=Host(`premiarteserver.lumau.com.ar`)"
      - "traefik.http.routers.premiarteserver.entrypoints=websecure"
      - "traefik.http.routers.premiarteserver.tls.certresolver=letsencrypt"
      - "traefik.http.services.premiarteserver.loadbalancer.server.port=1337"
      - "traefik.docker.network=coolify"
      - "traefik.http.routers.premiarteserver-http.rule=Host(`premiarteserver.lumau.com.ar`)"
      - "traefik.http.routers.premiarteserver-http.entrypoints=web"
      - "traefik.http.routers.premiarteserver-http.middlewares=redirect-to-https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"      
  
networks:
  coolify:
    external: true

volumes:
  uploads-volume:
  data-volume: